services:
  postgres:
    image: postgres:15-alpine
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

<<<<<<< HEAD
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
=======
    volumes:
      - pg_data:/var/lib/postgresql/data

>>>>>>> be2fbf7 (update the files)
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
<<<<<<< HEAD
      context: ./devops-bootcamp-linker-backend
=======
      context: ./linker-backend
>>>>>>> be2fbf7 (update the files)
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - app-network

  frontend:
    build:
<<<<<<< HEAD
      context: devops-bootcamp-linker-frontend
=======
      context: linker-frontend
>>>>>>> be2fbf7 (update the files)
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network

<<<<<<< HEAD
networks:
  app-network:
    driver: bridge

# volumes:
#   pgdata: # dd
=======
volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
>>>>>>> be2fbf7 (update the files)
