on:
    push:
        branches:
            - main
jobs:
    checkout-and-prep:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5

    run-devsecops:
        needs: checkout-and-prep
        if: always()
        secrets: inherit
        uses: ./.github/workflows/devsecops.yml
        permissions:
            contents: read
            packages: write

    build-and-deploy:
        needs: run-devsecops
        secrets: inherit
        if: always()
        uses: ./.github/workflows/frontend-ci.yml
        permissions:
            contents: read
            packages: write
